baseurl = "https://sowusu.github.io"
title = "Nana Kwame Owusu"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 10

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Nana Kwame Owusu"
    description = "Nana's Personal Website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatare.jpg"
    footercontent = "  "
    fixedbarContent = false
    fixedbarContentAfter = false

    hideCredits = false
    hideCopyright = false

    snsShare = false

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Email"
    weight = 1
    url = "mailto:nana@sakyiowusu.com"
    color = "#ffd700"
    faicon = "fa-envelope"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/nowusu"
    color = "#0077B5"
    faicon = "fa-linkedin"
[[params.social]]
    name = "Github"
    weight = 3
    url = "https://github.com/sowusu/"
    color = "#6e5494"
    faicon = "fa-github"
[[params.social]]
    name = "Medium"
    weight = 4
    url = "https://medium.com/@s.owusu45"
    color = "#347235"
    faicon = "fa-medium"
[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Nana Kwame Owusu"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Nana Kwame Owusu"
            info = "I am Nana Kwame Owusu and I am a fullstack developer using toolsets including, but not limited to, <b>Java</b>, <b>Swift</b>, <b>Node/Express</b> and <b>Vue</b>. Happy to meet you. You can check out my <a href='/posts/'>blog</a> and featured <a href='/projects/'>projects</a>." 
            description = "Nana's Personal Website"
            keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 2.0
                url = "https://medium.com/@s.owusu45"

            [[languages.en.menu.main]]
                name = "Projects"
                weight = 2.0
                url = "projects"
