baseurl = "/"
title = "Nana Kwame Owusu"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 10

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Nana Kwame Owusu"
    description = "Nana's Personal Website"
    keywords = "blog,developer,personal"
    info = " "
    avatarurl = "images/avatar.jpg"
    footercontent = true
    fixedbarContent = false
    fixedbarContentAfter = false

    hideCredits = false
    hideCopyright = false

    snsShare = false

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "LinkedIn"
    weight = 1
    url = "https://www.linkedin.com/in/nowusu"
[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/sowusu/"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/_sakyi_nie"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Nana Kwame Owusu"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Nana Kwame Owusu"
            info = "I am Nana Kwame (Na'ame) Owusu and I fullstack developer using toolsets including, but not limited to, Java, Swift, Node/Express, Angular and React (soon). Happy to meet you. You can check out my blog here -->"
            description = "Nana's Personal Website"
            keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 2.0
                url = "posts"

            [[languages.en.menu.main]]
                name = "Projects"
                weight = 3
                url = "projects"
